version: "3"
services:
  eureka-naming-server:
    image: netflix-eureka-naming-server:latest
    ports:
      - "8761:8761"
    networks:
      - opallios-microservice-net

networks:
  opallios-microservice-net: