version: "3"
services:
  eureka-naming-server:
    image: netflix-eureka-naming-server:latest
    ports:
      - "8761:8761"
    networks:
      - opallios-microservice-net
    deploy:
        resources:
            limits:
              cpus: 0.50
              memory: 512M
            reservations:
              cpus: 0.25
              memory: 128M
    

networks:
  opallios-microservice-net: